<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zxpay</groupId>
        <artifactId>payment-ddd</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>infrastructure</artifactId>
    <packaging>jar</packaging>

    <name>payment :: infrastructure</name>
    <description>
        出站适配器：通道 SDK 适配（微信/支付宝/京东/银联 + Stripe/PayPal/ApplePay/Antom/Worldpay）、
        持久化、分布式锁、幂等存储、消息发布、签名验签、配置中心。
        这里是唯一允许出现框架、SDK、中间件细节的地方。
    </description>

    <dependencies>
        <dependency>
            <groupId>com.zxpay</groupId>
            <artifactId>application</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
